name: Organize LeetCode Solutions

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requests
        run: pip install requests

      - name: Run Organizer
        run: python .github/scripts/organize_leetcode.py

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto organize LeetCode solutions"
            git push
          fi
